CREATE USER 'posuser'@'%'
IDENTIFIED BY 'P0S_u$s3r';

CREATE USER 'posuser'@'127.0.0.1'
IDENTIFIED BY 'P0S_u$s3r';

CREATE USER 'posuser'@'localhost'
IDENTIFIED BY 'P0S_u$s3r';

GRANT SELECT, INSERT, UPDATE, EXECUTE, DELETE, SHOW VIEW ON pos.* TO 'posuser'@'%';